version: '3'

services:
  mongodb:
    image: mongo:latest
    container_name: "mongodb"
    environment:
      - MONGO_DATA_DIR=/data/db
      - MONGO_LOG_DIR=/dev/null
    volumes:
      - /Volumes/data/DEVtmp_Docker/MongoDB/data/db:/data/db
      - ./data_import:/data_import
    ports:
      - 27017:27017
    command: mongod --smallfiles --logpath=/dev/null # --quiet
