version: '3'

services:
  mysqldb:
    image: mysql:latest
    ports:
      - "3306:3306"
    volumes:
    #  - db_data:/var/lib/mysql
      - /Volumes/data/DEVtmp_Docker/MySQL/data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: konbini
      MYSQL_USER: konbini
      MYSQL_PASSWORD: konbini

# volumes:
#     db_data:
