version: '3'

services:
  mysqldb:
    image: mysql:latest
    ports:
      - "3306:3306"
    volumes:
    #  - db_data:/var/lib/mysql
      - /Volumes/data/DEV/tmp_Docker/MySQL/data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: mysql
      MYSQL_USER: mysql
      MYSQL_PASSWORD: 123456

# volumes:
#     db_data:
