version: '3.1'

volumes:
  database_data:
    driver: local

services:
  postgresdb:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_DB: workhub
      POSTGRES_USER: nluser
      POSTGRES_PASSWORD: ToilaNguyen86
    ports:
      - 5432:5432
    volumes:
      - database_data:/var/lib/postgresql/data
