version: '3'

services:
  redis:
    image: redis:latest
    command: ["redis-server", "--appendonly", "yes"]
    ports:
      - "6379:6379"
    hostname: redis
    # networks:
    #   - redis-net
    volumes:
      - /Volumes/data/DEV/Docker/tmpDrive/Redis/data:/data

# networks:
#   redis-net:

# volumes:
#   redis-data:
