version: '3'

services:
  redis:
    image: redis #:4.0.5-alpine
    command: ["redis-server", "--appendonly", "yes"]
    ports:
      - "6379:6379"
    hostname: redis
    # networks:
    #   - redis-net
    volumes:
      - /Volumes/data/DEV/tmp_Docker/Redis/data:/data

# networks:
#   redis-net:

# volumes:
#   redis-data:
